/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alumno
 */


import javax.swing.*;
import java.util.ArrayList;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import java.awt.Color;

import java.awt.FlowLayout;
import java.awt.BorderLayout;


public class marco extends javax.swing.JFrame {

    /**
     * Creates new form marco
     */
    private ArrayList<grupo> grupos=new ArrayList <grupo>();
    
    public marco() {
        initComponents();
        agregarGrupos();
        actualizaCombos();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        comboElim = new javax.swing.JComboBox<>();
        btnEliminarP = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        tfModNom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnEspecial = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        comboMod = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("nombre del grupo ");

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        btnAgregar.setText("agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        comboElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboElimActionPerformed(evt);
            }
        });

        btnEliminarP.setText("Eliminar este grupo");
        btnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPActionPerformed(evt);
            }
        });

        btnModifica.setText("Modifica  a -->");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });

        tfModNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfModNomActionPerformed(evt);
            }
        });

        jLabel8.setText("nombre de grupo a modificar");

        btnEspecial.setText("Agrega Contactos al Grupo>>");
        btnEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecialActionPerformed(evt);
            }
        });

        btnVer.setText("ver grupos ");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        comboMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminarP)
                            .addComponent(btnEspecial, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(btnSalir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(comboElim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfModNom, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifica)
                        .addGap(18, 18, 18)
                        .addComponent(comboMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnVer))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarP)
                    .addComponent(comboElim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfModNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifica)
                    .addComponent(comboMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnEspecial))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        

    
    
    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        grupo p=new grupo();
        String nombre=tfNombre.getText();
        //Integer  age=new Integer(tfEdad.getText() );
        p.setNombre(nombre);
        //p.setEdad(age);
        grupos.add(p);
        comboElim.addItem(nombre);
        comboMod.addItem(nombre);
        
        
        
        
        
        //p.destruir();
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void comboElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboElimActionPerformed
        
       
        int indice=(int)comboElim.getSelectedIndex();
        
        System.out.println("Identifa el >>>>"+indice);
        
        
        //tfNombre.setText(personas.get(indice).getNombre() );
    }//GEN-LAST:event_comboElimActionPerformed

    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPActionPerformed
        
        
        int  indice=(int)comboElim.getSelectedIndex();
        
        
       limpiaCombos();
       
        System.out.println("Se ha eliminado a "+grupos.get(indice).toString() );
        grupos.remove(indice);
        actualizaCombos();
        
        
        
       
    }//GEN-LAST:event_btnEliminarPActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        // TODO add your handling code here:
        int indice=(int) comboMod.getSelectedIndex();
        
        
        
        
        String name=tfModNom.getText();

        limpiaCombos();
        grupos.get(indice).setNombre(name);
        //personas.get(indice).setEdad(age);
        actualizaCombos();
        tfModNom.setText(" ");
        
      
    
        

    }//GEN-LAST:event_btnModificaActionPerformed

    private void tfModNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfModNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfModNomActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        JFrame fver=new JFrame("Grupos agregados");
        JPanel panel=new JPanel();
        panel.setBackground(new Color(240,240,240));
        panel.setLayout(new FlowLayout());
        JButton salir=new JButton("Salir");
        JTextArea textA=new JTextArea(20,25);
        JScrollPane scroll=new JScrollPane(textA);
        
        String concatena="";
            for(int i=0;i<grupos.size();i++)concatena=concatena+grupos.get(i).toString();
            
            textA.setText(concatena);
        
        
                
        salir.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
                if(e.getSource()==salir){
                fver.setVisible(false);
                fver.dispose();
                
                }
                }
        });
        
        panel.add(scroll);
        panel.add(salir);
        fver.add(panel);
        fver.setVisible(true);
        fver.setSize(400,400);
        fver.setDefaultCloseOperation(fver.EXIT_ON_CLOSE);
        
        
    }//GEN-LAST:event_btnVerActionPerformed

    
    /*
    boton especial 
    
    
    */
    private void btnEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecialActionPerformed
        JFrame fi=new JFrame(" Agrega contactos al grupo");
        fi.setLayout(new BorderLayout() );
        JPanel p=new JPanel();
        JPanel q=new JPanel();
        p.setLayout(new FlowLayout() );
        q.setLayout(new FlowLayout() );
        
        //p.setBackground(new Color(2,159,211));
        //q.setBackground(new Color(2,159,211));
        
        JTextField tfnom=new JTextField(10);
        JTextField tfcorreo=new JTextField(10);
        
        JTextField tfMnom=new JTextField(10);
        JTextField tfMedad=new JTextField(10);
        
        
        
        JLabel lbnom=new JLabel("Nombre");
        JLabel lbcorreo=new JLabel("Correo");
        
        JLabel lbMnom=new JLabel("Nombre");
        JLabel lbMedad=new JLabel("Correo");
        
        
        JLabel lbcombo1=new JLabel("grupos existentes");
        JLabel lbcombo2=new JLabel("Miembros del grupo");
        JLabel lbInstrucciones=new JLabel("El elemento selecionado en lista 2 es al que se le aplicaran las sig. operaciones,para ver los cambios des-selecione el grupo y selecione de nuevo");
        
       
        
        
        
        JComboBox comboP=new JComboBox();
        JComboBox  comboI=new JComboBox();
        
        
  for(int i=0;i<grupos.size();i++)comboP.addItem(grupos.get(i).getNombre() );
   //for(int i=0;i<grupos.size();i++)comboP.addItem(grupos.get(i).toString() );
        
        JButton agregar=new JButton ("Agregar a >>>");
        agregar.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
                int indice=comboP.getSelectedIndex();
                String name=tfnom.getText();
                String correo = tfcorreo.getText();
                
                grupos.get(indice).addInvitado(name,correo);
                
                }
        
        });
        
        JButton modificar=new JButton("Modifica nombre del contacto");
        modificar.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
                int indice=comboP.getSelectedIndex();
                int  indice2=comboI.getSelectedIndex();
                ArrayList<contacto> Inv;
                Inv=grupos.get(indice).getInvitado();
                
                
                
                String name=tfMnom.getText();
                String correo = tfMedad.getText();
                
                Inv.get(indice2).setNombre(name);
                Inv.get(indice2).setCorreo(correo);
                
               
                
                
                
                
                }
        
        });
        
        
        
        JButton eliminar=new JButton("Quita del grupo");
        eliminar.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
                int indice=comboP.getSelectedIndex();
                int aEliminar=comboI.getSelectedIndex();
                //System.out.println(indice);
                ArrayList<grupo> I;
                comboI.removeAllItems();
                I=grupos.get(indice).getInvitado();
                I.remove(aEliminar);
                
                }
        });
        
    JButton ver=new JButton("Ver los contactos");
        ver.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
        JFrame fContactos=new JFrame("Contactos agregados");
        JPanel panel=new JPanel();
        panel.setBackground(new Color(240,240,240));
        panel.setLayout(new FlowLayout());
        JButton salir=new JButton("Salir");
        JTextArea textA=new JTextArea(20,25);
        JScrollPane scroll=new JScrollPane(textA);
        
        int selecionado=comboP.getSelectedIndex();
        
        ArrayList<contacto> c=grupos.get(selecionado).getInvitado();
        
        String concatena="";
            for(int i=0;i<c.size();i++)concatena=concatena+c.get(i).toString();
            
            textA.setText(concatena);
        
        
                
        salir.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent e){
                if(e.getSource()==salir){
                fContactos.setVisible(false);
                fContactos.dispose();
                
                }
                }
        });
        
        panel.add(scroll);
       
        panel.add(salir);
        fContactos.add(panel);
        fContactos.setVisible(true);
        fContactos.setSize(400,400);
        fContactos.setDefaultCloseOperation(fContactos.EXIT_ON_CLOSE);
                    
                
                }
        
        });
        
        
        
        
        JButton salir=new JButton("Salir");
        salir.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
            fi.setVisible(false);
            fi.dispose();
            
            
            }
        });
        
        
        comboP.addItemListener(new ItemListener(){
                public void itemStateChanged(ItemEvent e){
                int indice=comboP.getSelectedIndex();
                ArrayList<contacto> inv=grupos.get(indice).getInvitado();
                comboI.removeAllItems();
                
                
                        
                 for(int  i=0;i<inv.size();i++){
                        comboI.addItem(inv.get(i).getNombre() );
                        }
                
                       
                       
                }
            
        });
        
        
      
        
        p.add(lbnom);
        p.add(tfnom);
        p.add(lbcorreo);
        p.add(tfcorreo);
        p.add(agregar);
        p.add(lbcombo1);
        p.add(comboP);
        
    
        
        q.add(lbInstrucciones);
        q.add(lbcombo2);
        q.add(comboI);
        q.add(modificar);
        q.add(lbMnom);
        q.add(tfMnom);
        q.add(lbMedad);
        q.add(tfMedad);
       q.add(ver);
        q.add(eliminar);
        q.add(salir);
        
        fi.add(p,BorderLayout.NORTH);
        fi.add(q,BorderLayout.CENTER);
        fi.setVisible(true);
        fi.setSize(800,200);
        fi.setDefaultCloseOperation(fi.EXIT_ON_CLOSE);
        
       
    }//GEN-LAST:event_btnEspecialActionPerformed

    private void comboModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboModActionPerformed
        
        /*
        int indice=comboMod.getSelectedIndex();
        String name=personas.get(indice).getNombre();
        String age= Integer.toString(personas.get(indice).getEdad() );
        
        tfModNom.setText(name);
        tfModEd.setText(age);
        */
        
        
         
        
    }//GEN-LAST:event_comboModActionPerformed

    public void agregarGrupos(){
        
        
        
        grupos.add(new grupo("videojuegos") );
        grupos.get(0).addInvitado("Maria", "marimar@hotmail.com");
        grupos.get(0).addInvitado("Mariana", "Poo.agregacion@hotmail.com");
        grupos.get(0).addInvitado("Carmen", "Pozole.caliente@ipn.com");
        
        
        grupos.add(new grupo("lectura"));
        grupos.get(1).addInvitado("Paola", "cumbiamix@gmail.com");
        grupos.get(1).addInvitado("Raul", "composicion@gmail.com");
        
        grupos.add(new grupo("sin grupo") );
        grupos.get(2).addInvitado("Claudia", "Nube brillante@gmail.com");
        grupos.get(2).addInvitado("Luis", "vegueta.dbz@gmail.com");
        
        
        grupos.add(new grupo("videojuegos y lectura") );
        grupos.get(3).addInvitado("Ruben","navegante@gmail.com");
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

    
    
    }
    public void actualizaCombos(){
       
        
        for(int i=0;i<grupos.size();i++){
        comboElim.addItem(grupos.get(i).getNombre() );
        comboMod .addItem(grupos.get(i).getNombre() );
        }
        
        
    }
    public void limpiaCombos(){
    comboElim.removeAllItems();
    comboMod.removeAllItems();
    }
    
    
    
    
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(marco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(marco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(marco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(marco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new marco().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JButton btnEspecial;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox<String> comboElim;
    private javax.swing.JComboBox<String> comboMod;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfModNom;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
